# Generated by Django 4.2 on 2023-05-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='amount',
            field=models.CharField(max_length=200),
        ),
    ]
